version: '3.9'
services:
  loki:
    image: grafana/loki:2.4.1
    container_name: grafana-loki
    volumes:
      - loki_data:/data/loki
    environment:
      - TZ=${TZ}
    networks:
      - loki_net

  nginx-auth:
    image: laurentbel/nginx-basic-auth:latest
    container_name: nginx-auth-loki
    ports:
      - 83:80
    depends_on:
      - loki
    environment:
      - FORWARD_HOST=${FORWARD_HOST}
      - FORWARD_PORT=${FORWARD_PORT}
      - TZ=${TZ}
      - BASIC_USERNAME=${BASIC_USERNAME}
      - BASIC_PASSWORD=${BASIC_PASSWORD}
    networks:
      - loki_net

networks:
  loki_net:
    name: loki_net

volumes:
  loki_data:
